apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jdmapp
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: jdmapp
  chart:
    spec:
      chart: jdmapp
      version: 0.1.37
      sourceRef:
        kind: HelmRepository
        name: jdmapp-repo
        namespace: flux-system
