apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jdmapp
  namespace: staging
spec:
  releaseName: jdmapp
  chart:
    spec:
      chart: jdmapp
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: jdmapp-repo
        namespace: flux-system
  interval: 1m
  values:
    namespace: staging
    frontend:
      image:
        name: ronaldorb/jdm-cars-frontend
        tag: ronaldorb/jdm-cars-frontend:v1.0.13 # {"$imagepolicy": "flux-system:frontend-policy"}
    backend:
      image:
        name: ronaldorb/jdm-cars-backend
        tag: ronaldorb/jdm-cars-backend:v1.0.13 # {"$imagepolicy": "flux-system:backend-policy"}
    db:
      image:
        name: ronaldorb/jdm-cars-db
        tag: ronaldorb/jdm-cars-db:v1.0.13 # {"$imagepolicy": "flux-system:db-policy"}
