name: Update Helm chart version

on:
  schedule:
    - cron: '*/15 * * * *'  # cada 15 minutos
  workflow_dispatch:

jobs:
  update-chart-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Get latest chart version
        id: get_version
        run: |
          # Descarga index.yaml y extrae la última versión del chart jdmapp
          curl -s https://ronaldorodriguezbermudez.github.io/helm-chart-app/index.yaml > index.yaml
          version=$(yq e '.entries.jdmapp[0].version' index.yaml)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Update HelmRelease version
        run: |
          echo "Updating HelmRelease.yaml with version ${{ steps.get_version.outputs.version }}"
          sed -i "s/version: .*/version: ${{ steps.get_version.outputs.version }}/" ./clusters/staging/myapp/HelmRelease.yaml

      - name: Commit changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ./clusters/staging/myapp/HelmRelease.yaml
          git diff --cached --quiet || git commit -m "Update HelmRelease version to ${{ steps.get_version.outputs.version }}"
          git push
